export const dynamicColors = [
  { color: "#FF7043", colorName: "Deep orange" },
  { color: "#4DB6AC", colorName: "Teal" },
  { color: "#BA68C8", colorName: "Purple" },
  { color: "#7986CB", colorName: "Indigo" },
  { color: "#F06292", colorName: "Pink" },
  { color: "#81C784", colorName: "Green" },
  { color: "#64B5F6", colorName: "Blue" },
  { color: "#FFD54F", colorName: "Amber" },
  { color: "#A1887F", colorName: "Brown" },
  { color: "#E57373", colorName: "Red" },
  { color: "#AED581", colorName: "Light green" },
  { color: "#FFB74D", colorName: "Orange" },
  { color: "#4FC3F7", colorName: "Light blue" },
  { color: "#9575CD", colorName: "Deep purple" },
  { color: "#90A4AE", colorName: "Blue grey" },
  { color: "#00ACC1", colorName: "Cyan" },
  { color: "#F44336", colorName: "Strong red" },
  { color: "#CE93D8", colorName: "Soft purple" },
  { color: "#B0BEC5", colorName: "Muted grey" },
  { color: "#8D6E63", colorName: "Earthy brown" },
];
